import './globals.css'
import type { Metadata } from 'next'
import { Inter, Seymour_One, Bebas_Neue, } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const seymour = Seymour_One({
  weight: "400",
  subsets: ['latin']
})

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bebas.className}>{children}</body>
    </html>
  )
}


